# Generated by Django 5.0.2 on 2024-02-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charcode', models.CharField(max_length=32, verbose_name='Код валюты')),
                ('date', models.DateTimeField(verbose_name='Дата обновления')),
                ('rate', models.CharField(max_length=9, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курс',
            },
        ),
    ]
