# Generated by Django 5.0.2 on 2024-02-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-date', 'charcode'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курс'},
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Курс'),
        ),
    ]
