# Generated by Django 5.0.2 on 2024-02-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_alter_rate_options_alter_rate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Курс'),
        ),
    ]
